application: carrowoo-byte3
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /data
  static_dir: data
  application_readable: true
- url: /d3
  static_dir: d3
- url: /stylesheets
  static_dir: stylesheets
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: django
  version: latest
